// Curated Kenney CC0 samples. Provenance: art/audio-source/v7/selection.json
export const audioSamples = {
  "gun-0": "assets/audio/v7/gun-0.wav",
  "ice-0": "assets/audio/v7/ice-0.wav",
  "punch-0": "assets/audio/v7/punch-0.wav",
  "metal-0": "assets/audio/v7/metal-0.wav",
  "gun-1": "assets/audio/v7/gun-1.wav",
  "ice-1": "assets/audio/v7/ice-1.wav",
  "punch-1": "assets/audio/v7/punch-1.wav",
  "metal-1": "assets/audio/v7/metal-1.wav",
  "gun-2": "assets/audio/v7/gun-2.wav",
  "ice-2": "assets/audio/v7/ice-2.wav",
  "punch-2": "assets/audio/v7/punch-2.wav",
  "metal-2": "assets/audio/v7/metal-2.wav",
  "blade-0": "assets/audio/v7/blade-0.wav",
  "blade-1": "assets/audio/v7/blade-1.wav",
  "cloth-0": "assets/audio/v7/cloth-0.wav",
  "heavy-0": "assets/audio/v7/heavy-0.wav",
  "boom-0": "assets/audio/v7/boom-0.wav",
  "energy-0": "assets/audio/v7/energy-0.wav",
  "cloth-1": "assets/audio/v7/cloth-1.wav",
  "heavy-1": "assets/audio/v7/heavy-1.wav",
  "boom-1": "assets/audio/v7/boom-1.wav",
  "energy-1": "assets/audio/v7/energy-1.wav",
  gear: "assets/audio/v7/gear.wav",
  coin: "assets/audio/v7/coin.wav",
  bell: "assets/audio/v7/bell.wav",
} as const;
