from pathlib import Path
names={'gunner':'时间枪手','knight':'灰烬骑士','frost':'霜环术士','engineer':'机巧召唤师','reaper':'血刃猎手','husk':'骨兵','runner':'疾行魔','archer':'弩手','elite':'深渊守卫','boss':'裂隙领主'}
sections=[]
def strip(name,n,size,label,version):
 return f'<figure><div class="strip" style="--frames:{n};--size:{size}px;--width:{n*size}px;background-image:url(assets/{version}/{name}-run.png)"></div><figcaption>{label}<small>{n} 帧 · {size} × {size}</small></figcaption></figure>'
sections.append('<section><h2>五位英雄 · 六帧移动循环</h2><div class="grid">'+''.join(strip(k,6,128,names[k],'v2' if k in ['gunner','knight'] else 'v5') for k in ['gunner','knight','frost','engineer','reaper'])+'</div></section>')
sections.append('<section><h2>五类敌人 · 四帧移动循环</h2><div class="grid">'+''.join(strip('enemy-'+k,4,192 if k=='boss' else 128,names[k],'v5') for k in ['husk','runner','archer','elite','boss'])+'</div></section>')
icons=[('frost-step','霜步'),('frost-zone','寒霜领域'),('frost-bolt','极寒冰封'),('engineer-swap','磁力跃迁'),('engineer-turret','部署炮台'),('engineer-army','机械军团'),('reaper-dash','血影突刺'),('reaper-drain','汲血斩'),('reaper-harvest','猩红收割')]
sections.append('<section><h2>炮台与手绘技能图标</h2><div class="grid">'+'<figure><img src="assets/v5/turret.png" alt="青铜双管炮台"><figcaption>青铜双管炮台</figcaption></figure>'+''.join(f'<figure><img src="assets/v5/icon-{k}.png" alt="{n}"><figcaption>{n}</figcaption></figure>' for k,n in icons)+'</div></section>')
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>裂隙幸存者 · 动态美术画廊</title><style>
*{box-sizing:border-box}body{margin:0;background:#131b17;color:#ede4cf;font:16px/1.6 system-ui,sans-serif}main{max-width:1160px;margin:auto;padding:36px 24px}a{color:#8bd4c1}h1{font-size:32px;margin:20px 0 8px}h2{font-size:20px;color:#d6bb80;margin:40px 0 16px}.intro{color:#aeb5a4;max-width:740px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}figure{margin:0;padding:18px 12px;border:1px solid #455142;border-radius:12px;background:repeating-conic-gradient(#2b3328 0% 25%,#242c23 0% 50%) 50%/24px 24px;display:flex;flex-direction:column;justify-content:end;align-items:center;min-height:220px}.strip{width:var(--size);height:var(--size);background-size:var(--width) var(--size);animation:walk .75s steps(var(--frames)) infinite}@keyframes walk{to{background-position:calc(-1*var(--width)) 0}}figcaption{margin-top:14px;color:#e4d4ae}small{display:block;font-size:11px;color:#98a68f}img{width:128px;height:128px;object-fit:contain}button{padding:10px 20px;border:1px solid #819176;border-radius:6px;background:#283627;color:#e9dfc9;cursor:pointer;margin-top:14px}.paused .strip{animation-play-state:paused}.floor{width:100%;height:auto;border-radius:12px}@media(prefers-reduced-motion:reduce){.strip{animation:none}}@media(max-width:600px){.grid{grid-template-columns:1fr 1fr}figure{padding:10px;min-height:195px}.strip{transform:scale(.75);transform-origin:50% 100%;margin-top:-32px}h1{font-size:24px}}
</style><main><a href="/?v=0.5">← 返回游戏</a><h1>从静态角色，到会行动的战场。</h1><p class="intro">v0.5 · 五位英雄、五类敌人，共 50 帧移动动画。统一手绘轮廓、共享缩放与底部锚点。棋盘背景展示真实透明边缘；动画可以暂停以检查单帧。</p><button id="toggle" aria-pressed="false">暂停动画</button>'''+''.join(sections)+'''<section><h2>石质竞技场</h2><img class="floor" src="assets/v2/arena-floor.webp" alt="石质竞技场"></section><p class="intro">本次新增 38 帧。当前动画覆盖移动，攻击、受击、闪避、技能与待机呼吸仍由程序实现。游戏中的播放速度会按角色类型区分。</p></main><script>document.getElementById('toggle').addEventListener('click',e=>{const paused=document.body.classList.toggle('paused');e.target.textContent=paused?'播放动画':'暂停动画';e.target.setAttribute('aria-pressed',String(paused));});</script></html>'''
Path('public/art-gallery.html').write_text(html)
